# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, help_text='Short description of the Network Area.', max_length=100, null=True, verbose_name='Network area description')),
                ('address', models.PositiveIntegerField(help_text='Network area address.', verbose_name='Network area address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, help_text='Short description of the Network System.', max_length=100, null=True, verbose_name='System description')),
                ('name', models.CharField(help_text='Unique name of the system in the network.', max_length=50, verbose_name='System name')),
                ('areas', models.ManyToManyField(blank=True, to='network.Area')),
                ('connected_systems', models.ManyToManyField(blank=True, related_name='_system_connected_systems_+', to='network.System')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
